on: [push]

name: build

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run build
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: unbound-telemetry-${{ matrix.os }}
          path: ./target/release/unbound-telemetry
